# -*- mode: ruby -*-
# vi: set ft=ruby :

# Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian.wheezy"

  config.vm.box_url = "http://vagrantboxes.footballradar.com/wheezy64.box"

  # config.vm.network :forwarded_port, guest: 80, host: 8080
  # config.vm.network :private_network, ip: "192.168.33.10"
  # config.vm.network :public_network
  # config.ssh.forward_agent = true
  config.vm.synced_folder "..", "/opt/libsysinfo"

  # XXX : Using puppet to configure a VM to help writing an alternative to Puppet
  # XXX : Is not that called irony ?
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet"
    puppet.manifest_file  = "debian.pp"
  end
end
